### ISSUE TITLE
Maybe add ability to turn high CPU usage error off/on?

### ISSUE THREAD

**Issue by MrGoriay** [oliver-zehentleitner/unicorn-binance-websocket-api#124]
**Is your feature request related to a problem? Please describe.**
I understand that it is not hurting anyone, but i would still like to be able to turn 'High cpu usage' error off when needed.

**Describe the solution you'd like**
Some kind of function that will change some kind of flag or anything that will work, does not matter

**Additional context**
Great work with this library!

**Comment by oliver-zehentleitner** [comment]
this logging is new and it could be made better, for example log only if cpu is longer than X seconds touching 100% and yes we can add a flag to disable it.

I added it, because I recognized that if the server is often at 100% cpu usage, your streams are [restarting with error 1006](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/113) in cause of that! I guess every one wants to avoid that, because you are going to lose data between a reconnect.

**Comment by MrGoriay** [comment]
Thanks for quick reply. I understand, your solution is more flexible. It'll be great to see any solution in the next update. Thanks again for your effort.

**Comment by oliver-zehentleitner** [comment]
It think it should fit better now: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/commit/5d9434a3de137da4dcbccc144034c93cec94a6f5 

I will try to find the right balance for this and test how adequate the info is in the upcoming releases.
