### ISSUE TITLE
 'BinanceWebSocketApiManager' object has no attribute 'set_private_api_config'

### ISSUE THREAD

**Issue by just-a-normal-human** [oliver-zehentleitner/unicorn-binance-websocket-api#141]
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you using the module on a VPS or other Cloud hosting?
- [ ] Are you using the module on a Raspberry Pi?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)

#### Python Version Requirement
- [x] I am using Python 3.6.1 or above

#### Exact Python Version?
```
Python 3.7.9
```

#### Pip Version?
```
pip 9.0.3 
```

#### Description of your issue

When i run on my computer it all works fine, but when i try to run it on a ec2 server I get this error message. Wasnt `set_private_api_config` removed?

```
Traceback (most recent call last):
  File "mainStrat.py", line 87, in <module>
    binance_websocket_api_manager.set_private_api_config(binance_je_api_key, binance_je_api_secret)
AttributeError: 'BinanceWebSocketApiManager' object has no attribute 'set_private_api_config'
```

**Comment by oliver-zehentleitner** [comment]
pip 9 is very old, i use pip 20 :)
`python3 -m pip install --upgrade pip`

set_private_api_config() is deprecated and was finally removed in 1.28: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/releases/tag/1.28.0

**Comment by just-a-normal-human** [comment]
Oop, I upgraded it on my server. But why does the error occur if it doesn't exist and how would I go about fixing it?

**Comment by oliver-zehentleitner** [comment]
To give a solid answer, I would need more information about both systems (where it runs and where it doesn't). 

I assume you are using a version before 1.28.0 on the local PC where the method is still present. On your server I assume you already have 1.28.0 installed and get the error because you call a function/method that no longer exists.

What is the new way without `binance_websocket_api_manager.set_private_api_config(binance_je_api_key, binance_je_api_secret)`??

Use the new parameter of [`create_stream()`](https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html?highlight=create_stream#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.create_stream):
```
 ubwa.create_stream('arr', '!userData', api_key=api_key, api_secret=api_secret)
```

**Comment by oliver-zehentleitner** [comment]
I close this,
