### ISSUE TITLE
Websocket KEY expired

### ISSUE THREAD

**Issue by amaioli** [oliver-zehentleitner/unicorn-binance-websocket-api#184]
Hi, sometime happen that the websocket key expire on Binance side. In that case which is the best way to refresh it without create a new stream object?

**Comment by miraclix** [comment]
Can you post log file please

**Comment by amaioli** [comment]
I can provide the event issued by Binance. Is it enough?

Il Mer 21 Lug 2021, 12:02 miraclix ***@***.***> ha scritto:

**Comment by oliver-zehentleitner** [comment]
No, need to know what is happening inside ubwa
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by amaioli** [comment]
No logs and errors from it. It's happens on 12 of July to a lot of
different bots. Are there some way to increase the frequency of listen key
updating by the library?

Il Mer 21 Lug 2021, 12:32 Oliver Zehentleitner ***@***.***>
ha scritto:

**Comment by oliver-zehentleitner** [comment]
since 2 years i have had zero trounbles with listenkeys... if this is a rare error i would say its the best to catch it and to auto restart with a new listenkey... but i need a logfile to see what has happend, then i can update the lib. 
if no logs are there, please turn it on for the future and reopen this issue!
