### ISSUE TITLE
Please make the similar package for Bybit!

### ISSUE THREAD

**Issue by am11y** [oliver-zehentleitner/unicorn-binance-websocket-api#99]
I really like your websocket for binance, the most reliable one!

Please make similar package for Bybit exchange!

Best regards!

**Comment by oliver-zehentleitner** [comment]
Hello!

Thanks for the feedback, it makes me very happy to hear that!

I almost spent a year working on this lib. The hard stuff is testing over months, because a lot of problems happens only once in a couple of days or once in a month. I want to make this lib "perfect" - it should work without bugs and run the streams for ever... I am also learning a lot by doing this. I would love creating more libs, but as soon as this is ready, i want to finish unicorn_fy.

I need this 2 libs for my own too, but i never used bybit exchange.

Maybe someone else wants to fork ubwa (when its ready and fully bug free)  and make an adoption of it for bybit. I guess this can save them a lot of development time.

Best regards!
Oliver

**Comment by oliver-zehentleitner** [comment]
Here it is :)

https://github.com/LUCIT-Systems-and-Development/unicorn-bybit-websocket-api
https://pypi.org/project/unicorn-bybit-websocket-api/
https://anaconda.org/lucit/unicorn-bybit-websocket-api
